name: duplicate_checker
description: "A Flutter desktop web application for file comparison and duplicate detection."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.2.1
  path: ^1.9.1
  google_fonts: ^6.2.1
  flutter_dropzone: ^4.2.1
  provider: ^6.1.4
  path_provider: ^2.1.5
  universal_html: ^2.2.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
